### ISSUE TITLE
[Feature Request] Discord integration?

### ISSUE THREAD

**Issue by CyberSecGuy** [mark2devel/mark2#110]
Any way to integrate this with Discord webhooks?

**Comment by Trikolon** [comment]
You could probably add a Discord endpoint which extends HTTPEndpoint similar to what has been done for pushover: https://github.com/gsand/mark2/blob/master/mk2/plugins/push.py#L112

**Comment by Column01** [comment]
I know this is old, but still a good suggestion.

Do you have any suggestions for what you'd like to see added to a discord webhook?

**Comment by Column01** [comment]
I've started working on something for this. Currently, it's only on a [branch of my personal fork of mark2.](https://github.com/Column01/mark2/tree/discord-plugin)
Here is an example of it reacting to start/stop events and posting to discord:
![image](https://user-images.githubusercontent.com/26526649/128609547-884ff3ff-5a21-4132-8092-cca4d041a1d9.png)

**Comment by Column01** [comment]
A pull request has been submitted and should be accepted after it is reviewed 😄 
https://github.com/gsand/mark2/pull/133

**Comment by Column01** [comment]
I guess I can close this now since I already pulled the request. It's there, but maybe not as integrated as I'd like. When I get some time, mark3 (which is a full re-write of mark2) will probably have a proper discord integration with a chat bridge and events and such.
