### ISSUE TITLE
Cannot cancel a scheduled restart

### ISSUE THREAD

**Issue by Column01** [mark2devel/mark2#152]
![image](https://user-images.githubusercontent.com/26526649/135726065-9a86d9ca-fd9b-4abc-bb70-4fdb6a724bee.png)

**Comment by Column01** [comment]
I can't for the life of me figure out why this happens, sometimes it works fine to cancel a restart and other times it doesn't work at all

**Comment by edk0** [comment]
Shutdown's `self.cancel` doesn't get adjusted when one of the delayed events actually happens. That seems like a bug, and it could be the root cause of this.

**Comment by Column01** [comment]
Ahh I see, this seems to be the case. I can probably work something out where if it tries to cancel an ready completed event it just goes back and tries the next queue item until it either cancels something or the queue is empty

**Comment by Column01** [comment]
If a server restarts multiple times those cancel events potentially build up over time too as far as I can tell. Might need to implement something that clears the queue of completed events instead of the other idea

**Comment by Column01** [comment]
> Shutdown's `self.cancel` doesn't get adjusted when one of the delayed events actually happens. That seems like a bug, and it could be the root cause of this.

I know this is kind of old at this point but I'm looking into it and the actual error comes [here](https://github.com/mark2devel/mark2/blob/ae62c5dc8739fc3b9598b43c921c11a5b5e922db/mk2/plugins/__init__.py#L251-L254)

Am I stupid to think I could just fix this by checking if the task is active before trying to cancel it? Or should I be looking at fixing what you mentioned where the events are not cleared in shutdown. Cause it seems to me this could happen for _any_ task that is being run in a plugin that can be cancelled

```py
def cancel(*args):
    if delayed_call[0].active():
        delayed_call[0].cancel()
        if callbackCancel:
            callbackCancel(*args)
```

**Comment by Column01** [comment]
I was correct in my assumption, should push a fix here in a bit
