### ISSUE TITLE
Velocity proxy sample configuration

### ISSUE THREAD

**Issue by synrg** [mark2devel/mark2#163]
I have started playing with Velocity, a more modern, secure, featureful BungeeCord proxy replacement. I think mark2 should include a sample configuration. I include my mark2.properties so far below to kick off the discussion. I'm sure it can be improved upon.

```ini
# based on samples/bungeecord/mark2.properties and https://velocitypowered.com/wiki/users/getting-started/
mark2.jar-path=velocity*.jar
mark2.service.process.done-pattern=Done \(.*\)\!
mark2.service.process.stop-cmd=end\n
mark2.regex.join=\\[connected player\\] (?P<username>[A-Za-z0-9_]{1,16}) \\(\\/(?P<ip>.+)\\) has connected
mark2.regex.quit=\\[connected player\\] (?P<username>[A-Za-z0-9_]{1,16}).* has disconnected(: )?(?P<reason>.*)
java.cli_prepend=-XX:+UnlockExperimentalVMOptions
java.cli.X.ms=512M
java.cli.X.mx=512M
java.cli.XX.UseG1GC=true
java.cli.XX.ParallelRefProcEnabled=true
java.cli.XX.AlwaysPreTouch=true
java.cli.XX.G1HeapRegionSize=4M
plugin.monitor.crash-unknown-cmd-message=.*command.*does not exist.*
# requires Velocity Utils plugin: https://forums.velocitypowered.com/t/velocity-utils-useful-commands-like-send-and-find/825
plugin.shutdown.alert-command=alert %s
plugin.backup.enabled=false
plugin.save.enabled=false
plugin.trigger.enabled=false
```

**Comment by synrg** [comment]
FYI, there is no built in "alert" command for Velocity, so `plugin.shutdown.alert-command=alert %s` does nothing and should probably be removed. https://velocitypowered.com/wiki/users/built-in-commands/

I'm investigating whether whatever this is supposed to accomplish (warn people in advance of a scheduled shutdown, I assume?) can be done with a Velocity plugin.

**Comment by Column01** [comment]
Generally the JVM args would not be included in the sample. As for alerts, it's probably not needed, I think it was just there to show how you can do that with mark2. I'd encourage making a pull request instead of an issue 😉
