### ISSUE TITLE
How to prevent /kick after stop and restart?

### ISSUE THREAD

**Issue by Elgorond** [mark2devel/mark2#170]
For compatibility with a plugin called MySQL Player Data Bridge, I need to prevent mark2 from kicking players (with /kick) upon server restart.

![Screenshot (302)](https://user-images.githubusercontent.com/8552780/203401269-2944e7f6-9184-4bc1-9776-6f58af7aa91c.png)

Is the /kick feature necessary for mark2 to work properly? If so, is there a way for me to use the command /mpdb saveAndKick (executed one time) instead of having it /kick every player?

**Comment by edk0** [comment]
In your mark2.properties:
```
plugin.shutdown.kick-mode=once
plugin.shutdown.kick-command=mpdb saveAndKick
```
