### ISSUE TITLE
monitor: Paper 1.20.6 + enable-status=false breaks crash monitor

### ISSUE THREAD

**Issue by synrg** [mark2devel/mark2#180]
Running mark2 master with Paper 1.20.6, the settings that formerly worked with 1.20.4 no longer work for crash monitoring. If the response is expected to be only a single line, that might be why this problem has only emerged now, since in 1.20.6, Paper now outputs two lines instead of one.

### Steps to reproduce

Mark2 is configured as follows in the server's `mark2.properties` file in the same dir as the paper*.jar file:

```
plugin.monitor.crash-unknown-cmd-message=.*Unknown.*command.*
```

Paper 1.20.4 output for crash check command with all plugins disabled:

```
[08:44:09] [Server thread/INFO]: Unknown command. Type "/help" for help.
[08:45:09] [Server thread/INFO]: Unknown command. Type "/help" for help.
```

The next test is the same server with same mark2 settings. The only change is the replacement of the Paper .jar file with 1.20.6.

Paper 1.20.6 output:
```
[08:47:50] [Server thread/INFO]: Unknown or incomplete command, see below for error
/~mark2CrashCheck~<--[HERE]
[08:48:50] [Server thread/INFO]: Stopping the server
[08:48:50] [Server thread/INFO]: Stopping the server
[08:48:50] [Server thread/INFO]: Unknown or incomplete command, see below for error
/~mark2CrashCheck~<--[HERE]
[08:48:50] [Server thread/INFO]: Stopping server
...
```

The corresponding `server-*-not accepting connections` output:
```
2024-12-05 08:47:50 | ESC[38;2;255;85;85mUnknown or incomplete command, see below for error
2024-12-05 08:47:50 | [RAW] ESC[38;2;170;170;170mESC[4mESC[38;2;255;85;85m/~mark2CrashCheck~ESC[0mESC[3mESC[38;2;255;85;85m<--[HERE]ESC[0m
2024-12-05 08:48:49 # server might have crashed: not accepting accepting console commands or crash-unknown-cmd-message is not set -- restarting.
2024-12-05 08:48:49 # stopping minecraft-survival-09 (caused by crashed)
2024-12-05 08:48:49 # server might have crashed: not accepting connections or wrong port is being pinged. -- restarting.
2024-12-05 08:48:49 # stopping minecraft-survival-09 (caused by not accepting connections)
2024-12-05 08:48:50 | Stopping the server
2024-12-05 08:48:50 | Stopping the server
2024-12-05 08:48:50 | ESC[38;2;255;85;85mUnknown or incomplete command, see below for error
2024-12-05 08:48:50 | [RAW] ESC[38;2;170;170;170mESC[4mESC[38;2;255;85;85m/~mark2CrashCheck~ESC[0mESC[3mESC[38;2;255;85;85m<--[HERE]ESC[0m
2024-12-05 08:48:50 | Stopping server
```

In the mark2 console itself, I see:

![image](https://github.com/user-attachments/assets/1228a57f-5c41-417d-b689-4849d0b7f5bb)

i.e. it successfully eats the first line that the pattern matches, but not the second one. Perhaps this indicates mark2 doesn't expect the second line, and therefore has no way to fully match the response?

Ultimately I couldn't figure out how to construct a regex that would work to match the crash ping response. Nor could I devise an alternate crash command that mark2 could successfully match with some other pattern.

I had sufficient doubts that it would be as simple as patching mark2 to do multiline matches - I guessed it's probably literally reading back just a single line - that I didn't attempt further analysis of the code or a patch along those lines.

### Workaround:

After all my failed attempts, and without any clear ideas as to an approach to fix this issue, I had to disable the monitor plugin to avoid having mark2 respond to this false positive crash detect and take down the server repeatedly. This is not ideal, as then I lose that functionality. I hope it's not too difficult to fix, as it would be nice to have crash monitoring back again on this version of Paper!

p.s. Ideally I would have upgraded all of the way to Paper 1.21.x which now has stable builds, but the plugins our community has come to rely on don't work yet. Therefore, I haven't yet tested that version, but I can try that one too if it would help.

**Comment by synrg** [comment]
Thanks. The pattern turned out to not be the problem. My original pattern matches the response just as well. However, I did find one setting that *mostly* resolved this issue, at least as far as allowing me to reenable crash monitoring and not have it take down the server. Tidying the output is the only part of this issue that remains unresolved.

### Solution to the false positive

In `server.properties`, I discovered I had `enable-status=false`, but a second server that I tested had `enable-status=true` on Paper 1.20.6, and yet it had no false positives with the crash monitor running. When made the second server like the first by setting `enable-status=true`, the crash monitor stopped seeing the server as crashed after the 2nd ping, causing unnecessary restarts.

The thing I don't understand is why did `enable-status=false` work with Paper 1.20.4, but not with 1.20.6? Does that have anything to do with the second message being emitted or is it more likely something else, like a change in implementation of that setting between the two Paper versions.

### Unresolved: pings no longer silent

The only unresolved part of this issue is for a good user experience with Paper 1.20.6 is the output is flooded with messages now whereas previously the crash checks were entirely silent ...

Since mark2 only matches and eats the expected command output itself and not the second line, the console quickly fills up with `[RAW] /~mark2CrashCheck~<--[HERE]` "noise", scrolling away any actual messages from activity on the server that I would like to see. I'm faced with having to scroll past a thousand or more lines of this to get to the good stuff.

Is there some way you can help with this? Apart from turning off monitoring again, or at least drastically decreasing the frequence of the pings, I don't know what I can do without delving into the code.

**Comment by Column01** [comment]
Reading this again the monitor was killing it because it wasn't accepting connections which is determined by pinging the server and `enable-status` will affect that. No idea why it worked before but it shouldn't have lol

As for the duplicate lines, its a side affect of the message becoming a multiline response in newer mc, it could probably be fixed with some simple filtering but i'm struggling with carpal tunnel atm and can't write any code

**Comment by synrg** [comment]
Sorry to hear that. I can't promise I'll have time for it, but if I do, I'll take a look and see if it's simple enough for me to patch it myself.

**Comment by Column01** [comment]
> Sorry to hear that. I can't promise I'll have time for it, but if I do, I'll take a look and see if it's simple enough for me to patch it myself.

That would be good ;)

If you want a good starting point I'd look at the monitor plugin and see how it filters the first part of unknown command message and try and replicate that for lines that have the crash check command in it

**Comment by Column01** [comment]
Looking into adding this

**Comment by Column01** [comment]
If you'd like to have `enable-status` set to false, you can disable the monitor's pinging functionality by adding this to your server's `mark2.properties` file:

`plugin.monitor.ping-enabled=false`

If you'd like to fix the second crash check message, you'll have to stop your servers (fully off of the wrapper for safety) and pull the latest mark2 version from github. 

Once you've done that, you'll need to add this to your mark2 user config (`~/.config/mark2/mark2.properties` for your Minecraft server user). Alternatively, if you've never made changes to that file, you could just delete that folder and run `mark2 config` again to generate an updated one

```
# For newer MC versions, this will filter out the second "~mark2CrashCheck<---HERE" line
plugin.monitor.crash-check-command-message=.*~mark2CrashCheck~.*
```

Feel free to reply if you have any other questions or concerns.

Thanks!

Colin

**Comment by synrg** [comment]
Oh hey, that's great! Yep, seems to work just fine. I haven't set back `enable-status=false` as we don't actually need it - it was just a holdover from an earlier setup we forgot about.
